# This workflow will build and test the solution Password Genie.sln when a pull request is created or updated.

name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build
